version: "3.8"
services:
  # Symfony apache project container
  ui:
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
    container_name: ui_cosmic
    hostname: ui_cosmic
    ports:
      - 3001:3000
    volumes:
      - ./nuxt:/app
    restart: always
    networks:
      - cosmic

networks:
  cosmic:
    external:
      name: cosmic